apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stanford-students-api.fullname" . }}-config
  namespace: {{ .Values.namespace | default "student-api" }}
  labels:
    {{- include "stanford-students-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.app.port | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  POSTGRES_DB: {{ .Values.app.database.name | quote }}
  POSTGRES_USER: {{ .Values.app.database.user | quote }}