apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stanford-students-api.fullname" . }}
  namespace: {{ .Values.namespace | default "student-api" }}
  labels:
    {{- include "stanford-students-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stanford-students-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stanford-students-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: db-migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["/usr/local/bin/migrate"]
        args:
        - "-path"
        - "/app/database/migrations"
        - "-database"
        - "$(DATABASE_URL)"
        - "up"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DATABASE_URL
          value: "postgres://{{ .Values.app.database.user }}:$(POSTGRES_PASSWORD)@{{ include "stanford-students-api.fullname" . }}-postgresql:5432/{{ .Values.app.database.name }}?sslmode=disable"
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: PORT
          value: {{ .Values.app.port | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.app.logLevel | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.app.database.name | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.app.database.user | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DATABASE_URL
          value: "postgres://{{ .Values.app.database.user }}:$(POSTGRES_PASSWORD)@{{ include "stanford-students-api.fullname" . }}-postgresql:5432/{{ .Values.app.database.name }}?sslmode=disable"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}