apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "student-api" }}
  labels:
    name: {{ .Values.namespace | default "student-api" }}
    {{- include "stanford-students-api.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets