apiVersion: v1
kind: Service
metadata:
  name: {{ include "stanford-students-api.fullname" . }}
  namespace: {{ .Values.namespace | default "student-api" }}
  labels:
    {{- include "stanford-students-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "stanford-students-api.selectorLabels" . | nindent 4 }}