version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: stanford_students
      POSTGRES_USER: admin_stan
      POSTGRES_PASSWORD: admin12345
    ports:
      - "5433:5432"  # External port 5433, internal port 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Host volume for persistence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_stan -d stanford_students"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://admin_stan:admin12345@postgres:5432/stanford_students?sslmode=disable
      PORT: 8080
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

# Using host directory binding instead of named volumes
# Data will be stored in ./postgres_data/ directory