---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api
  labels:
    name: student-api
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
    environment: development